import type {
  PlatformUser,
  Customer,
  Transaction,
  Report,
  DashboardStats,
} from "../Types/types";

// ─── Platform Users ───────────────────────────────────────────────────────────

export const mockUsers: PlatformUser[] = [
  // {
  //   _id: "u1",
  //   fullName: "Priya Sharma",
  //   email: "priya.sharma@gmail.com",
  //   phone: "+91 98765 43210",
  //   dob: "1990-03-14",
  //   tob: "06:30",
  //   pob: "Mumbai, Maharashtra",
  //   pobCity: "Mumbai",
  //   pobCountry: "India",
  //   primaryConcern: "Career & Finance",
  //   additionalNotes: "Looking for guidance on switching careers to spirituality",
  //   plan: "premium",
  //   status: "active",
  //   registeredAt: "2024-01-15T08:30:00Z",
  //   lastLogin: "2024-07-10T14:20:00Z",
  // },
  // {
  //   _id: "u2",
  //   fullName: "Arjun Mehta",
  //   email: "arjun.mehta@yahoo.com",
  //   phone: "+91 87654 32109",
  //   dob: "1985-07-22",
  //   tob: "14:45",
  //   pob: "Delhi, India",
  //   pobCity: "New Delhi",
  //   pobCountry: "India",
  //   primaryConcern: "Marriage & Relationships",
  //   additionalNotes: "Seeking kundali matching for upcoming marriage",
  //   plan: "modern",
  //   status: "active",
  //   registeredAt: "2024-02-20T10:00:00Z",
  //   lastLogin: "2024-07-09T09:15:00Z",
  // },
  // {
  //   _id: "u3",
  //   fullName: "Kavitha Nair",
  //   email: "kavitha.nair@outlook.com",
  //   phone: "+91 76543 21098",
  //   dob: "1995-11-05",
  //   tob: "22:10",
  //   pob: "Kochi, Kerala",
  //   pobCity: "Kochi",
  //   pobCountry: "India",
  //   primaryConcern: "Health & Wellness",
  //   additionalNotes: "Recurring health issues, wants planetary remedies",
  //   plan: "free",
  //   status: "active",
  //   registeredAt: "2024-03-08T16:45:00Z",
  //   lastLogin: "2024-07-08T11:30:00Z",
  // },
  // {
  //   _id: "u4",
  //   fullName: "Rohan Verma",
  //   email: "rohan.verma@gmail.com",
  //   phone: "+91 65432 10987",
  //   dob: "1988-05-18",
  //   tob: "09:00",
  //   pob: "Jaipur, Rajasthan",
  //   pobCity: "Jaipur",
  //   pobCountry: "India",
  //   primaryConcern: "Business & Investments",
  //   additionalNotes: "Wants muhurta for business launch",
  //   plan: "premium",
  //   status: "active",
  //   registeredAt: "2024-01-30T12:00:00Z",
  //   lastLogin: "2024-07-10T16:00:00Z",
  // },
  // {
  //   _id: "u5",
  //   fullName: "Sunita Patel",
  //   email: "sunita.patel@rediffmail.com",
  //   phone: "+91 54321 09876",
  //   dob: "1992-08-30",
  //   tob: "18:55",
  //   pob: "Ahmedabad, Gujarat",
  //   pobCity: "Ahmedabad",
  //   pobCountry: "India",
  //   primaryConcern: "Spiritual Growth",
  //   plan: "modern",
  //   status: "inactive",
  //   registeredAt: "2024-04-12T09:20:00Z",
  //   lastLogin: "2024-06-15T10:00:00Z",
  // },
  // {
  //   _id: "u6",
  //   fullName: "Deepak Iyer",
  //   email: "deepak.iyer@gmail.com",
  //   phone: "+91 43210 98765",
  //   dob: "1978-12-01",
  //   tob: "03:20",
  //   pob: "Chennai, Tamil Nadu",
  //   pobCity: "Chennai",
  //   pobCountry: "India",
  //   primaryConcern: "Family & Children",
  //   additionalNotes: "Wants to understand child's horoscope",
  //   plan: "premium",
  //   status: "active",
  //   registeredAt: "2024-02-01T07:30:00Z",
  //   lastLogin: "2024-07-07T08:45:00Z",
  // },
  // {
  //   _id: "u7",
  //   fullName: "Meena Krishnan",
  //   email: "meena.k@gmail.com",
  //   phone: "+91 32109 87654",
  //   dob: "1997-02-14",
  //   tob: "12:00",
  //   pob: "Bengaluru, Karnataka",
  //   pobCity: "Bengaluru",
  //   pobCountry: "India",
  //   primaryConcern: "Career & Finance",
  //   plan: "free",
  //   status: "active",
  //   registeredAt: "2024-05-22T14:00:00Z",
  //   lastLogin: "2024-07-10T19:30:00Z",
  // },
];

// ─── Customers ────────────────────────────────────────────────────────────────

export const mockCustomers: Customer[] = [
  // {
  //   _id: "c1", _Id: "u1",
  //   name: "Priya Sharma", email: "priya.sharma@gmail.com", phone: "+91 98765 43210",
  //   plan: "premium", planStartDate: "2024-01-15", planEndDate: "2025-01-15",
  //   amountPaid: 4999, currency: "INR", status: "active", reportsCount: 3,
  //   dateOfBirth: "1990-03-14", timeOfBirth: "06:30",
  //   placeOfBirth: "Mumbai, Maharashtra", cityOfBirth: "Mumbai", countryOfBirth: "India",
  //   primaryConcern: "Career & Finance",
  //   additionalNotes: "Looking for guidance on switching careers to spirituality",
  // },
  // {
  //   _id: "c2", _Id: "u2",
  //   name: "Arjun Mehta", email: "arjun.mehta@yahoo.com", phone: "+91 87654 32109",
  //   plan: "modern", planStartDate: "2024-02-20", planEndDate: "2024-08-20",
  //   amountPaid: 1999, currency: "INR", status: "active", reportsCount: 1,
  //   dateOfBirth: "1985-07-22", timeOfBirth: "14:45",
  //   placeOfBirth: "Delhi, India", cityOfBirth: "New Delhi", countryOfBirth: "India",
  //   primaryConcern: "Marriage & Relationships",
  //   additionalNotes: "Seeking kundali matching for upcoming marriage",
  // },
  // {
  //   id: "c3", userId: "u4",
  //   name: "Rohan Verma", email: "rohan.verma@gmail.com", phone: "+91 65432 10987",
  //   plan: "premium", planStartDate: "2024-01-30", planEndDate: "2025-01-30",
  //   amountPaid: 4999, currency: "INR", status: "active", reportsCount: 2,
  //   dateOfBirth: "1988-05-18", timeOfBirth: "09:00",
  //   placeOfBirth: "Jaipur, Rajasthan", cityOfBirth: "Jaipur", countryOfBirth: "India",
  //   primaryConcern: "Business & Investments",
  //   additionalNotes: "Wants muhurta for business launch",
  // },
  // {
  //   id: "c4", userId: "u5",
  //   name: "Sunita Patel", email: "sunita.patel@rediffmail.com", phone: "+91 54321 09876",
  //   plan: "modern", planStartDate: "2024-04-12", planEndDate: "2024-10-12",
  //   amountPaid: 1999, currency: "INR", status: "active", reportsCount: 1,
  //   dateOfBirth: "1992-08-30", timeOfBirth: "18:55",
  //   placeOfBirth: "Ahmedabad, Gujarat", cityOfBirth: "Ahmedabad", countryOfBirth: "India",
  //   primaryConcern: "Spiritual Growth",
  // },
  // {
  //   id: "c5", userId: "u6",
  //   name: "Deepak Iyer", email: "deepak.iyer@gmail.com", phone: "+91 43210 98765",
  //   plan: "premium", planStartDate: "2024-02-01", planEndDate: "2025-02-01",
  //   amountPaid: 4999, currency: "INR", status: "active", reportsCount: 4,
  //   dateOfBirth: "1978-12-01", timeOfBirth: "03:20",
  //   placeOfBirth: "Chennai, Tamil Nadu", cityOfBirth: "Chennai", countryOfBirth: "India",
  //   primaryConcern: "Family & Children",
  //   additionalNotes: "Wants to understand child's horoscope",
  // },
];

// ─── Transactions ─────────────────────────────────────────────────────────────

export const mockTransactions: Transaction[] = [
  // {
  //   id: "t1", userId: "u1", userName: "Priya Sharma", userEmail: "priya.sharma@gmail.com",
  //   plan: "premium", amount: 4999, currency: "INR", status: "success",
  //   gateway: "razorpay", transactionRef: "pay_OA123456789",
  //   createdAt: "2024-01-15T08:35:00Z", description: "Premium Annual Plan",
  // },
  // {
  //   id: "t2", userId: "u2", userName: "Arjun Mehta", userEmail: "arjun.mehta@yahoo.com",
  //   plan: "modern", amount: 1999, currency: "INR", status: "success",
  //   gateway: "stripe", transactionRef: "ch_3OB234567890",
  //   createdAt: "2024-02-20T10:05:00Z", description: "Modern 6-Month Plan",
  // },
  // {
  //   id: "t3", userId: "u3", userName: "Kavitha Nair", userEmail: "kavitha.nair@outlook.com",
  //   plan: "free", amount: 0, currency: "INR", status: "success",
  //   gateway: "razorpay", transactionRef: "free_OC345678901",
  //   createdAt: "2024-03-08T16:50:00Z", description: "Free Plan Activation",
  // },
  // {
  //   id: "t4", userId: "u4", userName: "Rohan Verma", userEmail: "rohan.verma@gmail.com",
  //   plan: "premium", amount: 4999, currency: "INR", status: "success",
  //   gateway: "razorpay", transactionRef: "pay_OD456789012",
  //   createdAt: "2024-01-30T12:05:00Z", description: "Premium Annual Plan",
  // },
  // {
  //   id: "t5", userId: "u5", userName: "Sunita Patel", userEmail: "sunita.patel@rediffmail.com",
  //   plan: "modern", amount: 1999, currency: "INR", status: "success",
  //   gateway: "paypal", transactionRef: "PAY-OE567890123",
  //   createdAt: "2024-04-12T09:25:00Z", description: "Modern 6-Month Plan",
  // },
  // {
  //   id: "t6", userId: "u6", userName: "Deepak Iyer", userEmail: "deepak.iyer@gmail.com",
  //   plan: "premium", amount: 4999, currency: "INR", status: "success",
  //   gateway: "razorpay", transactionRef: "pay_OF678901234",
  //   createdAt: "2024-02-01T07:35:00Z", description: "Premium Annual Plan",
  // },
  // {
  //   id: "t7", userId: "u7", userName: "Meena Krishnan", userEmail: "meena.k@gmail.com",
  //   plan: "free", amount: 0, currency: "INR", status: "pending",
  //   gateway: "razorpay", transactionRef: "pay_OG789012345",
  //   createdAt: "2024-05-22T14:05:00Z", description: "Free Plan Activation",
  // },
  // {
  //   id: "t8", userId: "u2", userName: "Arjun Mehta", userEmail: "arjun.mehta@yahoo.com",
  //   plan: "premium", amount: 4999, currency: "INR", status: "failed",
  //   gateway: "stripe", transactionRef: "ch_3OH890123456",
  //   createdAt: "2024-07-01T11:00:00Z", description: "Premium Upgrade Attempt",
  // },
];

// ─── Reports ──────────────────────────────────────────────────────────────────

export const mockReports: Report[] = [
  // {
  //   id: "r1", userId: "u1", userName: "Priya Sharma", userEmail: "priya.sharma@gmail.com",
  //   title: "Annual Vedic Horoscope — Priya Sharma (2024)",
  //   content: `<h2>Natal Chart Analysis</h2><p>Based on the birth details provided, Priya's Lagna (Ascendant) is <strong>Pisces</strong> with Jupiter as the lord in the 7th house, creating a powerful Dharma Karma Adhipati Yoga.</p><h2>Career Insights</h2><p>The 10th lord Jupiter is well-placed in Virgo, indicating success in advisory and consultative roles. Rahu's transit through the 11th house in 2024 will bring unexpected gains and new professional networks.</p><h2>Key Planetary Positions</h2><ul><li>Sun: Aries (2nd house) — Strong financial acumen</li><li>Moon: Cancer (5th house) — Creative intelligence, emotional intelligence</li><li>Mars: Scorpio (9th house) — Passionate about dharma and higher learning</li></ul><h2>Remedies</h2><p>Chanting the Vishnu Sahasranama on Thursdays and wearing a Yellow Sapphire (Pukhraj) on the index finger of the right hand is recommended to strengthen Jupiter.</p>`,
  //   template: "premium",
  //   status: "sent",
  //   createdAt: "2024-02-10T10:30:00Z",
  //   sentAt: "2024-02-10T11:00:00Z",
  // },
  // {
  //   id: "r2", userId: "u2", userName: "Arjun Mehta", userEmail: "arjun.mehta@yahoo.com",
  //   title: "Kundali Matching Report — Arjun & Partner",
  //   content: `<h2>Compatibility Analysis</h2><p>The Ashtakoot matching shows <strong>28 out of 36 points</strong>, indicating excellent compatibility for marriage.</p><h2>Guna Milan Breakdown</h2><ul><li>Varna: 1/1</li><li>Vashya: 2/2</li><li>Tara: 3/3</li><li>Yoni: 4/4</li><li>Graha Maitri: 5/5</li><li>Gana: 6/6</li><li>Bhakoot: 7/7</li></ul>`,
  //   template: "modern",
  //   status: "sent",
  //   createdAt: "2024-03-15T14:00:00Z",
  //   sentAt: "2024-03-15T15:30:00Z",
  // },
  // {
  //   id: "r3", userId: "u4", userName: "Rohan Verma", userEmail: "rohan.verma@gmail.com",
  //   title: "Business Muhurta & Financial Forecast 2024",
  //   content: `<h2>Auspicious Dates for Business Launch</h2><p>Based on your natal chart, the most auspicious windows for launching your business in 2024 are: <strong>April 14–18</strong> and <strong>September 3–7</strong>.</p>`,
  //   template: "premium",
  //   status: "created",
  //   createdAt: "2024-07-08T09:00:00Z",
  // },
  // {
  //   id: "r4", userId: "u6", userName: "Deepak Iyer", userEmail: "deepak.iyer@gmail.com",
  //   title: "Child's Horoscope — Comprehensive Analysis",
  //   content: `<h2>Child's Birth Chart Overview</h2><p>The child's Lagna is Gemini, with Mercury as the lagna lord placed in the 5th house — indicating a highly intellectual and creative child with a natural flair for communication.</p>`,
  //   template: "premium",
  //   status: "draft",
  //   createdAt: "2024-07-10T08:00:00Z",
  // },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const mockStats: DashboardStats = {
  totalUsers: 7,
  totalCustomers: 5,
  totalRevenue: 22994,
  totalReports: 4,
  usersGrowth: 23.5,
  revenueGrowth: 18.2,
  reportsThisMonth: 2,
  activeSubscriptions: 5,
};

// ─── Revenue Chart Data ───────────────────────────────────────────────────────

export const revenueChartData = [
  { month: "Jan", revenue: 9998, users: 2 },
  { month: "Feb", revenue: 4999, users: 1 },
  { month: "Mar", revenue: 1999, users: 1 },
  { month: "Apr", revenue: 1999, users: 1 },
  { month: "May", revenue: 0, users: 1 },
  { month: "Jun", revenue: 0, users: 0 },
  { month: "Jul", revenue: 0, users: 1 },
];

export const planDistributionData = [
  { name: "Free", value: 2, color: "#6d28d9" },
  { name: "Modern", value: 2, color: "#f59e0b" },
  { name: "Premium", value: 3, color: "#10b981" },
];
